// Command e2e measures how grpc-gateway turns an HTTP request into the gRPC
// request message. It is not a model of grpc-gateway: the handlers are the code
// protoc-gen-grpc-gateway generates for the descriptor set (produced by
// scripts/regen-vectors.sh through ./protogen), registered on a
// runtime.ServeMux and pointed at an in-process gRPC server that records the
// bytes it receives.
//
//	e2e <descriptor set> <source> < cases.json > vectors.json
//
// A vector is either the request message the server received (in
// deterministic binary and, for reading, as JSON) or the HTTP error the
// gateway answered instead.
package main

import (
	"bufio"
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"sync"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/encoding"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/test/bufconn"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/dynamicpb"
)

type requestCase struct {
	Name    string      `json:"name"`
	Mux     string      `json:"mux,omitempty"`
	Method  string      `json:"method"`
	Target  string      `json:"target"`
	Headers [][2]string `json:"headers,omitempty"`
	Body    string      `json:"body,omitempty"`
}

type cases struct {
	Cases []requestCase `json:"cases"`
}

type statusBody struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type outcome struct {
	// Outcome is "request" when the gRPC server received a request, "error"
	// when the gateway answered without calling it.
	Outcome string `json:"outcome"`
	// RPC is the full method the server was called with.
	RPC string `json:"rpc,omitempty"`
	// Message is the request in deterministic protobuf binary, base64.
	Message     string          `json:"message,omitempty"`
	MessageJSON json.RawMessage `json:"message_json,omitempty"`
	Status      int             `json:"status,omitempty"`
	// Errors are the google.rpc.Status bodies written, in order: a malformed
	// path escape writes one per candidate before the final answer.
	Errors []statusBody `json:"errors,omitempty"`
	// RawBody is kept when the body is not a sequence of Status objects.
	RawBody string `json:"raw_body,omitempty"`
}

type vector struct {
	requestCase
	outcome
}

type vectors struct {
	Generator string   `json:"generator"`
	Source    string   `json:"source"`
	Notes     string   `json:"notes"`
	Vectors   []vector `json:"vectors"`
	Dropped   []string `json:"dropped_nondeterministic,omitempty"`
}

const notes = "Handlers generated by protoc-gen-grpc-gateway (allow_patch_feature=true, " +
	"repeated_path_param_separator=csv) from the descriptor set, on a runtime.ServeMux, calling an " +
	"in-process gRPC server through bufconn. message is what that server received, re-encoded " +
	"deterministically. protojson error prefixes are recorded as \"proto: \" (the build may use a " +
	"no-break space, internal/detrand) and error bodies without protojson's random spaces. A case " +
	"whose answer changes between runs (Go map order over query keys or HTTP methods) is dropped."

// rawCodec lets the recording server take any method's request as bytes.
type rawCodec struct{}

func (rawCodec) Marshal(v any) ([]byte, error) { return *(v.(*[]byte)), nil }
func (rawCodec) Unmarshal(data []byte, v any) error {
	*(v.(*[]byte)) = append([]byte(nil), data...)
	return nil
}
func (rawCodec) Name() string { return "proto" }

var _ encoding.Codec = rawCodec{}

type received struct {
	rpc string
	msg []byte
}

type recorder struct {
	mu  sync.Mutex
	got []received
}

func (r *recorder) handle(_ any, stream grpc.ServerStream) error {
	rpc, _ := grpc.MethodFromServerStream(stream)
	var msg []byte
	if err := stream.RecvMsg(&msg); err != nil {
		return err
	}
	r.mu.Lock()
	r.got = append(r.got, received{rpc: rpc, msg: msg})
	r.mu.Unlock()
	empty := []byte{}
	return stream.SendMsg(&empty)
}

func (r *recorder) take() []received {
	r.mu.Lock()
	defer r.mu.Unlock()
	got := r.got
	r.got = nil
	return got
}

func main() {
	grpclog.SetLoggerV2(grpclog.NewLoggerV2(io.Discard, io.Discard, io.Discard))
	if len(os.Args) != 3 {
		fail("usage: e2e <descriptor set> <source> < cases.json")
	}
	services := servicesOf(os.Args[1])
	var c cases
	if err := json.NewDecoder(os.Stdin).Decode(&c); err != nil {
		fail("decode cases: %v", err)
	}

	rec := &recorder{}
	lis := bufconn.Listen(1 << 20)
	srv := grpc.NewServer(grpc.UnknownServiceHandler(rec.handle), grpc.ForceServerCodec(rawCodec{}))
	go func() { _ = srv.Serve(lis) }()
	defer srv.Stop()
	conn, err := grpc.NewClient("passthrough:///bufconn",
		grpc.WithContextDialer(func(ctx context.Context, _ string) (net.Conn, error) { return lis.DialContext(ctx) }),
		grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		fail("dial: %v", err)
	}
	defer conn.Close()

	muxes := map[string]*runtime.ServeMux{}
	for name, opts := range map[string][]runtime.ServeMuxOption{
		"":                    nil,
		"no_fallback":         {runtime.WithDisablePathLengthFallback()},
		"all_except_reserved": {runtime.WithUnescapingMode(runtime.UnescapingModeAllExceptReserved)},
		"all_characters":      {runtime.WithUnescapingMode(runtime.UnescapingModeAllCharacters)},
	} {
		mux := runtime.NewServeMux(opts...)
		// The order the services are registered in decides which handler wins
		// a request two of them match: declaration order, as the contract
		// vectors assume.
		for _, s := range services {
			register, ok := registry[s]
			if !ok {
				fail("service %s has HTTP rules but no Register*HandlerClient in register.go", s)
			}
			if err := register(context.Background(), mux, conn); err != nil {
				fail("register %s: %v", s, err)
			}
		}
		muxes[name] = mux
	}

	out := vectors{Generator: os.Getenv("ABADA_GENERATOR"), Source: os.Args[2], Notes: notes}
	seen := map[string]bool{}
	for _, rc := range c.Cases {
		if seen[rc.Name] {
			fail("case %s: duplicate name", rc.Name)
		}
		seen[rc.Name] = true
		mux, ok := muxes[rc.Mux]
		if !ok {
			fail("case %s: unknown mux %q", rc.Name, rc.Mux)
		}
		first := run(mux, rec, rc)
		stable := true
		for i := 0; i < 16 && stable; i++ {
			stable = same(first, run(mux, rec, rc))
		}
		if !stable {
			out.Dropped = append(out.Dropped, rc.Name)
			continue
		}
		out.Vectors = append(out.Vectors, vector{requestCase: rc, outcome: first})
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(out); err != nil {
		fail("encode: %v", err)
	}
}

// servicesOf lists, in declaration order, the services of the set that have
// at least one google.api.http rule.
func servicesOf(path string) []string {
	raw, err := os.ReadFile(path)
	if err != nil {
		fail("%v", err)
	}
	var set descriptorpb.FileDescriptorSet
	if err := proto.Unmarshal(raw, &set); err != nil {
		fail("%s: %v", path, err)
	}
	var names []string
	for _, f := range set.GetFile() {
		for _, s := range f.GetService() {
			for _, m := range s.GetMethod() {
				if proto.HasExtension(m.GetOptions(), annotations.E_Http) {
					names = append(names, f.GetPackage()+"."+s.GetName())
					break
				}
			}
		}
	}
	return names
}

func run(mux *runtime.ServeMux, rec *recorder, rc requestCase) outcome {
	var raw bytes.Buffer
	fmt.Fprintf(&raw, "%s %s HTTP/1.1\r\nHost: gateway\r\n", rc.Method, rc.Target)
	for _, h := range rc.Headers {
		fmt.Fprintf(&raw, "%s: %s\r\n", h[0], h[1])
	}
	fmt.Fprintf(&raw, "Content-Length: %d\r\n\r\n%s", len(rc.Body), rc.Body)
	req, err := http.ReadRequest(bufio.NewReader(&raw))
	if err != nil {
		fail("case %s: net/http refuses the request: %v", rc.Name, err)
	}
	w := httptest.NewRecorder()
	rec.take()
	mux.ServeHTTP(w, req)
	got := rec.take()
	switch len(got) {
	case 0:
	case 1:
		return requestOutcome(rc, got[0])
	default:
		fail("case %s: %d calls", rc.Name, len(got))
	}
	o := outcome{Outcome: "error", Status: w.Code}
	body := w.Body.String()
	for len(body) > 0 {
		end := topLevelEnd(body)
		var s statusBody
		if end == len(body) && !strings.HasSuffix(body, "}") || json.Unmarshal([]byte(body[:end]), &s) != nil {
			o.Errors = nil
			o.RawBody = w.Body.String()
			break
		}
		s.Message = strings.ReplaceAll(s.Message, "proto: ", "proto: ")
		o.Errors = append(o.Errors, s)
		body = body[end:]
	}
	return o
}

func requestOutcome(rc requestCase, r received) outcome {
	name := strings.TrimPrefix(r.rpc, "/")
	svc, method, ok := strings.Cut(name, "/")
	if !ok {
		fail("case %s: rpc %q", rc.Name, r.rpc)
	}
	d, err := protoregistry.GlobalFiles.FindDescriptorByName(protoreflect.FullName(svc))
	if err != nil {
		fail("case %s: %v", rc.Name, err)
	}
	md := d.(protoreflect.ServiceDescriptor).Methods().ByName(protoreflect.Name(method))
	msg := dynamicpb.NewMessage(md.Input())
	if err := proto.Unmarshal(r.msg, msg); err != nil {
		fail("case %s: request does not decode: %v", rc.Name, err)
	}
	bin, err := proto.MarshalOptions{Deterministic: true}.Marshal(msg)
	if err != nil {
		fail("case %s: %v", rc.Name, err)
	}
	o := outcome{Outcome: "request", RPC: r.rpc, Message: base64.StdEncoding.EncodeToString(bin)}
	if js, err := (protojson.MarshalOptions{UseProtoNames: true}).Marshal(msg); err == nil {
		// Through encoding/json: sorted keys and no random spaces, so the
		// readable copy is as stable as the binary one.
		var v any
		if err := json.Unmarshal(js, &v); err != nil {
			fail("case %s: %v", rc.Name, err)
		}
		o.MessageJSON, _ = json.Marshal(v)
	}
	return o
}

func same(a, b outcome) bool {
	x, _ := json.Marshal(a)
	y, _ := json.Marshal(b)
	return bytes.Equal(x, y)
}

// topLevelEnd is the length of the first JSON object at the start of s, or
// len(s) when s does not start with one.
func topLevelEnd(s string) int {
	if !strings.HasPrefix(s, "{") {
		return len(s)
	}
	depth, inString, escaped := 0, false, false
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case inString && escaped:
			escaped = false
		case inString && c == '\\':
			escaped = true
		case c == '"':
			inString = !inString
		case !inString && c == '{':
			depth++
		case !inString && c == '}':
			depth--
			if depth == 0 {
				return i + 1
			}
		}
	}
	return len(s)
}

func fail(f string, a ...any) {
	fmt.Fprintf(os.Stderr, "e2e: "+f+"\n", a...)
	os.Exit(1)
}
