// Messages for the JSON conformance vectors: every field shape protojson
// treats differently, including the ones no real contract of abada uses yet.
// Compiled by conformance/protos/generate.sh; not a public API.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: abada/conformance/v1/json.proto

package abadapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_RED         Color = 1
	Color_COLOR_GREEN       Color = 2
	Color_COLOR_NEGATIVE    Color = -1
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0:  "COLOR_UNSPECIFIED",
		1:  "COLOR_RED",
		2:  "COLOR_GREEN",
		-1: "COLOR_NEGATIVE",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_RED":         1,
		"COLOR_GREEN":       2,
		"COLOR_NEGATIVE":    -1,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_abada_conformance_v1_json_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_abada_conformance_v1_json_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_abada_conformance_v1_json_proto_rawDescGZIP(), []int{0}
}

type Alias int32

const (
	Alias_ALIAS_ZERO Alias = 0
	Alias_ALIAS_ONE  Alias = 1
	Alias_ALIAS_UNO  Alias = 1
)

// Enum value maps for Alias.
var (
	Alias_name = map[int32]string{
		0: "ALIAS_ZERO",
		1: "ALIAS_ONE",
		// Duplicate value: 1: "ALIAS_UNO",
	}
	Alias_value = map[string]int32{
		"ALIAS_ZERO": 0,
		"ALIAS_ONE":  1,
		"ALIAS_UNO":  1,
	}
)

func (x Alias) Enum() *Alias {
	p := new(Alias)
	*p = x
	return p
}

func (x Alias) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alias) Descriptor() protoreflect.EnumDescriptor {
	return file_abada_conformance_v1_json_proto_enumTypes[1].Descriptor()
}

func (Alias) Type() protoreflect.EnumType {
	return &file_abada_conformance_v1_json_proto_enumTypes[1]
}

func (x Alias) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Alias.Descriptor instead.
func (Alias) EnumDescriptor() ([]byte, []int) {
	return file_abada_conformance_v1_json_proto_rawDescGZIP(), []int{1}
}

type Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Child         *Nested                `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_abada_conformance_v1_json_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_abada_conformance_v1_json_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_abada_conformance_v1_json_proto_rawDescGZIP(), []int{0}
}

func (x *Nested) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Nested) GetChild() *Nested {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *Nested) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Every scalar kind, singular, without presence. Declared out of number order
// on purpose: protojson writes fields in declaration order.
type Scalars struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LateDeclaredLowNumber string                 `protobuf:"bytes,99,opt,name=late_declared_low_number,json=lateDeclaredLowNumber,proto3" json:"late_declared_low_number,omitempty"`
	I32                   int32                  `protobuf:"varint,1,opt,name=i32,proto3" json:"i32,omitempty"`
	I64                   int64                  `protobuf:"varint,2,opt,name=i64,proto3" json:"i64,omitempty"`
	U32                   uint32                 `protobuf:"varint,3,opt,name=u32,proto3" json:"u32,omitempty"`
	U64                   uint64                 `protobuf:"varint,4,opt,name=u64,proto3" json:"u64,omitempty"`
	S32                   int32                  `protobuf:"zigzag32,5,opt,name=s32,proto3" json:"s32,omitempty"`
	S64                   int64                  `protobuf:"zigzag64,6,opt,name=s64,proto3" json:"s64,omitempty"`
	Fx32                  uint32                 `protobuf:"fixed32,7,opt,name=fx32,proto3" json:"fx32,omitempty"`
	Fx64                  uint64                 `protobuf:"fixed64,8,opt,name=fx64,proto3" json:"fx64,omitempty"`
	Sfx32                 int32                  `protobuf:"fixed32,9,opt,name=sfx32,proto3" json:"sfx32,omitempty"`
	Sfx64                 int64                  `protobuf:"fixed64,10,opt,name=sfx64,proto3" json:"sfx64,omitempty"`
	Flt                   float32                `protobuf:"fixed32,11,opt,name=flt,proto3" json:"flt,omitempty"`
	Dbl                   float64                `protobuf:"fixed64,12,opt,name=dbl,proto3" json:"dbl,omitempty"`
	Flag                  bool                   `protobuf:"varint,13,opt,name=flag,proto3" json:"flag,omitempty"`
	Str                   string                 `protobuf:"bytes,14,opt,name=str,proto3" json:"str,omitempty"`
	Byt                   []byte                 `protobuf:"bytes,15,opt,name=byt,proto3" json:"byt,omitempty"`
	Color                 Color                  `protobuf:"varint,16,opt,name=color,proto3,enum=abada.conformance.v1.Color" json:"color,omitempty"`
	Alias                 Alias                  `protobuf:"varint,17,opt,name=alias,proto3,enum=abada.conformance.v1.Alias" json:"alias,omitempty"`
	Custom                string                 `protobuf:"bytes,18,opt,name=custom,json=renamed,proto3" json:"custom,omitempty"`
	SnakeCaseName         string                 `protobuf:"bytes,19,opt,name=snake_case_name,json=snakeCaseName,proto3" json:"snake_case_name,omitempty"`
	Name_1A               string                 `protobuf:"bytes,20,opt,name=name_1a,json=name1a,proto3" json:"name_1a,omitempty"`
	X_                    string                 `protobuf:"bytes,21,opt,name=x_,json=x,proto3" json:"x_,omitempty"`
	Nested                *Nested                `protobuf:"bytes,22,opt,name=nested,proto3" json:"nested,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Scalars) Reset() {
	*x = Scalars{}
	mi := &file_abada_conformance_v1_json_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scalars) ProtoMessage() {}

func (x *Scalars) ProtoReflect() protoreflect.Message {
	mi := &file_abada_conformance_v1_json_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scalars.ProtoReflect.Descriptor instead.
func (*Scalars) Descriptor() ([]byte, []int) {
	return file_abada_conformance_v1_json_proto_rawDescGZIP(), []int{1}
}

func (x *Scalars) GetLateDeclaredLowNumber() string {
	if x != nil {
		return x.LateDeclaredLowNumber
	}
	return ""
}

func (x *Scalars) GetI32() int32 {
	if x != nil {
		return x.I32
	}
	return 0
}

func (x *Scalars) GetI64() int64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (x *Scalars) GetU32() uint32 {
	if x != nil {
		return x.U32
	}
	return 0
}

func (x *Scalars) GetU64() uint64 {
	if x != nil {
		return x.U64
	}
	return 0
}

func (x *Scalars) GetS32() int32 {
	if x != nil {
		return x.S32
	}
	return 0
}

func (x *Scalars) GetS64() int64 {
	if x != nil {
		return x.S64
	}
	return 0
}

func (x *Scalars) GetFx32() uint32 {
	if x != nil {
		return x.Fx32
	}
	return 0
}

func (x *Scalars) GetFx64() uint64 {
	if x != nil {
		return x.Fx64
	}
	return 0
}

func (x *Scalars) GetSfx32() int32 {
	if x != nil {
		return x.Sfx32
	}
	return 0
}

func (x *Scalars) GetSfx64() int64 {
	if x != nil {
		return x.Sfx64
	}
	return 0
}

func (x *Scalars) GetFlt() float32 {
	if x != nil {
		return x.Flt
	}
	return 0
}

func (x *Scalars) GetDbl() float64 {
	if x != nil {
		return x.Dbl
	}
	return 0
}

func (x *Scalars) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *Scalars) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *Scalars) GetByt() []byte {
	if x != nil {
		return x.Byt
	}
	return nil
}

func (x *Scalars) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Scalars) GetAlias() Alias {
	if x != nil {
		return x.Alias
	}
	return Alias_ALIAS_ZERO
}

func (x *Scalars) GetCustom() string {
	if x != nil {
		return x.Custom
	}
	return ""
}

func (x *Scalars) GetSnakeCaseName() string {
	if x != nil {
		return x.SnakeCaseName
	}
	return ""
}

func (x *Scalars) GetName_1A() string {
	if x != nil {
		return x.Name_1A
	}
	return ""
}

func (x *Scalars) GetX_() string {
	if x != nil {
		return x.X_
	}
	return ""
}

func (x *Scalars) GetNested() *Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

type Repeated struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	I32           []int32                  `protobuf:"varint,1,rep,packed,name=i32,proto3" json:"i32,omitempty"`
	I64           []int64                  `protobuf:"varint,2,rep,packed,name=i64,proto3" json:"i64,omitempty"`
	U32           []uint32                 `protobuf:"varint,3,rep,packed,name=u32,proto3" json:"u32,omitempty"`
	U64           []uint64                 `protobuf:"varint,4,rep,packed,name=u64,proto3" json:"u64,omitempty"`
	S32           []int32                  `protobuf:"zigzag32,5,rep,packed,name=s32,proto3" json:"s32,omitempty"`
	S64           []int64                  `protobuf:"zigzag64,6,rep,packed,name=s64,proto3" json:"s64,omitempty"`
	Fx32          []uint32                 `protobuf:"fixed32,7,rep,packed,name=fx32,proto3" json:"fx32,omitempty"`
	Fx64          []uint64                 `protobuf:"fixed64,8,rep,packed,name=fx64,proto3" json:"fx64,omitempty"`
	Sfx32         []int32                  `protobuf:"fixed32,9,rep,packed,name=sfx32,proto3" json:"sfx32,omitempty"`
	Sfx64         []int64                  `protobuf:"fixed64,10,rep,packed,name=sfx64,proto3" json:"sfx64,omitempty"`
	Flt           []float32                `protobuf:"fixed32,11,rep,packed,name=flt,proto3" json:"flt,omitempty"`
	Dbl           []float64                `protobuf:"fixed64,12,rep,packed,name=dbl,proto3" json:"dbl,omitempty"`
	Flag          []bool                   `protobuf:"varint,13,rep,packed,name=flag,proto3" json:"flag,omitempty"`
	Str           []string                 `protobuf:"bytes,14,rep,name=str,proto3" json:"str,omitempty"`
	Byt           [][]byte                 `protobuf:"bytes,15,rep,name=byt,proto3" json:"byt,omitempty"`
	Color         []Color                  `protobuf:"varint,16,rep,packed,name=color,proto3,enum=abada.conformance.v1.Color" json:"color,omitempty"`
	Nested        []*Nested                `protobuf:"bytes,17,rep,name=nested,proto3" json:"nested,omitempty"`
	Ts            []*timestamppb.Timestamp `protobuf:"bytes,18,rep,name=ts,proto3" json:"ts,omitempty"`
	Any           []*anypb.Any             `protobuf:"bytes,19,rep,name=any,proto3" json:"any,omitempty"`
	Value         []*structpb.Value        `protobuf:"bytes,20,rep,name=value,proto3" json:"value,omitempty"`
	I64Wrapper    []*wrapperspb.Int64Value `protobuf:"bytes,21,rep,name=i64_wrapper,json=i64Wrapper,proto3" json:"i64_wrapper,omitempty"`
	Null          []structpb.NullValue     `protobuf:"varint,22,rep,packed,name=null,proto3,enum=google.protobuf.NullValue" json:"null,omitempty"`
	St            []*structpb.Struct       `protobuf:"bytes,23,rep,name=st,proto3" json:"st,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repeated) Reset() {
	*x = Repeated{}
	mi := &file_abada_conformance_v1_json_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repeated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repeated) ProtoMessage() {}

func (x *Repeated) ProtoReflect() protoreflect.Message {
	mi := &file_abada_conformance_v1_json_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repeated.ProtoReflect.Descriptor instead.
func (*Repeated) Descriptor() ([]byte, []int) {
	return file_abada_conformance_v1_json_proto_rawDescGZIP(), []int{2}
}

func (x *Repeated) GetI32() []int32 {
	if x != nil {
		return x.I32
	}
	return nil
}

func (x *Repeated) GetI64() []int64 {
	if x != nil {
		return x.I64
	}
	return nil
}

func (x *Repeated) GetU32() []uint32 {
	if x != nil {
		return x.U32
	}
	return nil
}

func (x *Repeated) GetU64() []uint64 {
	if x != nil {
		return x.U64
	}
	return nil
}

func (x *Repeated) GetS32() []int32 {
	if x != nil {
		return x.S32
	}
	return nil
}

func (x *Repeated) GetS64() []int64 {
	if x != nil {
		return x.S64
	}
	return nil
}

func (x *Repeated) GetFx32() []uint32 {
	if x != nil {
		return x.Fx32
	}
	return nil
}

func (x *Repeated) GetFx64() []uint64 {
	if x != nil {
		return x.Fx64
	}
	return nil
}

func (x *Repeated) GetSfx32() []int32 {
	if x != nil {
		return x.Sfx32
	}
	return nil
}

func (x *Repeated) GetSfx64() []int64 {
	if x != nil {
		return x.Sfx64
	}
	return nil
}

func (x *Repeated) GetFlt() []float32 {
	if x != nil {
		return x.Flt
	}
	return nil
}

func (x *Repeated) GetDbl() []float64 {
	if x != nil {
		return x.Dbl
	}
	return nil
}

func (x *Repeated) GetFlag() []bool {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *Repeated) GetStr() []string {
	if x != nil {
		return x.Str
	}
	return nil
}

func (x *Repeated) GetByt() [][]byte {
	if x != nil {
		return x.Byt
	}
	return nil
}

func (x *Repeated) GetColor() []Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Repeated) GetNested() []*Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Repeated) GetTs() []*timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Repeated) GetAny() []*anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

func (x *Repeated) GetValue() []*structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Repeated) GetI64Wrapper() []*wrapperspb.Int64Value {
	if x != nil {
		return x.I64Wrapper
	}
	return nil
}

func (x *Repeated) GetNull() []structpb.NullValue {
	if x != nil {
		return x.Null
	}
	return nil
}

func (x *Repeated) GetSt() []*structpb.Struct {
	if x != nil {
		return x.St
	}
	return nil
}

type Optionals struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	I32           *int32                 `protobuf:"varint,1,opt,name=i32,proto3,oneof" json:"i32,omitempty"`
	I64           *int64                 `protobuf:"varint,2,opt,name=i64,proto3,oneof" json:"i64,omitempty"`
	U32           *uint32                `protobuf:"varint,3,opt,name=u32,proto3,oneof" json:"u32,omitempty"`
	U64           *uint64                `protobuf:"varint,4,opt,name=u64,proto3,oneof" json:"u64,omitempty"`
	Flt           *float32               `protobuf:"fixed32,11,opt,name=flt,proto3,oneof" json:"flt,omitempty"`
	Dbl           *float64               `protobuf:"fixed64,12,opt,name=dbl,proto3,oneof" json:"dbl,omitempty"`
	Flag          *bool                  `protobuf:"varint,13,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	Str           *string                `protobuf:"bytes,14,opt,name=str,proto3,oneof" json:"str,omitempty"`
	Byt           []byte                 `protobuf:"bytes,15,opt,name=byt,proto3,oneof" json:"byt,omitempty"`
	Color         *Color                 `protobuf:"varint,16,opt,name=color,proto3,enum=abada.conformance.v1.Color,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Optionals) Reset() {
	*x = Optionals{}
	mi := &file_abada_conformance_v1_json_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Optionals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Optionals) ProtoMessage() {}

func (x *Optionals) ProtoReflect() protoreflect.Message {
	mi := &file_abada_conformance_v1_json_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Optionals.ProtoReflect.Descriptor instead.
func (*Optionals) Descriptor() ([]byte, []int) {
	return file_abada_conformance_v1_json_proto_rawDescGZIP(), []int{3}
}

func (x *Optionals) GetI32() int32 {
	if x != nil && x.I32 != nil {
		return *x.I32
	}
	return 0
}

func (x *Optionals) GetI64() int64 {
	if x != nil && x.I64 != nil {
		return *x.I64
	}
	return 0
}

func (x *Optionals) GetU32() uint32 {
	if x != nil && x.U32 != nil {
		return *x.U32
	}
	return 0
}

func (x *Optionals) GetU64() uint64 {
	if x != nil && x.U64 != nil {
		return *x.U64
	}
	return 0
}

func (x *Optionals) GetFlt() float32 {
	if x != nil && x.Flt != nil {
		return *x.Flt
	}
	return 0
}

func (x *Optionals) GetDbl() float64 {
	if x != nil && x.Dbl != nil {
		return *x.Dbl
	}
	return 0
}

func (x *Optionals) GetFlag() bool {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return false
}

func (x *Optionals) GetStr() string {
	if x != nil && x.Str != nil {
		return *x.Str
	}
	return ""
}

func (x *Optionals) GetByt() []byte {
	if x != nil {
		return x.Byt
	}
	return nil
}

func (x *Optionals) GetColor() Color {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

type Maps struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	I32           map[int32]string                   `protobuf:"bytes,1,rep,name=i32,proto3" json:"i32,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	I64           map[int64]string                   `protobuf:"bytes,2,rep,name=i64,proto3" json:"i64,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	U32           map[uint32]string                  `protobuf:"bytes,3,rep,name=u32,proto3" json:"u32,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	U64           map[uint64]string                  `protobuf:"bytes,4,rep,name=u64,proto3" json:"u64,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	S32           map[int32]string                   `protobuf:"bytes,5,rep,name=s32,proto3" json:"s32,omitempty" protobuf_key:"zigzag32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	S64           map[int64]string                   `protobuf:"bytes,6,rep,name=s64,proto3" json:"s64,omitempty" protobuf_key:"zigzag64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fx32          map[uint32]string                  `protobuf:"bytes,7,rep,name=fx32,proto3" json:"fx32,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fx64          map[uint64]string                  `protobuf:"bytes,8,rep,name=fx64,proto3" json:"fx64,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sfx32         map[int32]string                   `protobuf:"bytes,9,rep,name=sfx32,proto3" json:"sfx32,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sfx64         map[int64]string                   `protobuf:"bytes,10,rep,name=sfx64,proto3" json:"sfx64,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Flag          map[bool]string                    `protobuf:"bytes,11,rep,name=flag,proto3" json:"flag,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Str           map[string]string                  `protobuf:"bytes,12,rep,name=str,proto3" json:"str,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Byt           map[string][]byte                  `protobuf:"bytes,13,rep,name=byt,proto3" json:"byt,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Color         map[string]Color                   `protobuf:"bytes,14,rep,name=color,proto3" json:"color,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=abada.conformance.v1.Color"`
	Nested        map[string]*Nested                 `protobuf:"bytes,15,rep,name=nested,proto3" json:"nested,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Dbl           map[string]float64                 `protobuf:"bytes,16,rep,name=dbl,proto3" json:"dbl,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	I64Value      map[string]int64                   `protobuf:"bytes,17,rep,name=i64_value,json=i64Value,proto3" json:"i64_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Value         map[string]*structpb.Value         `protobuf:"bytes,18,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ts            map[string]*timestamppb.Timestamp  `protobuf:"bytes,19,rep,name=ts,proto3" json:"ts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StrWrapper    map[string]*wrapperspb.StringValue `protobuf:"bytes,20,rep,name=str_wrapper,json=strWrapper,proto3" json:"str_wrapper,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Flt           map[string]float32                 `protobuf:"bytes,21,rep,name=flt,proto3" json:"flt,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	FlagValue     map[string]bool                    `protobuf:"bytes,22,rep,name=flag_value,json=flagValue,proto3" json:"flag_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	U32Value      map[string]uint32                  `protobuf:"bytes,23,rep,name=u32_value,json=u32Value,proto3" json:"u32_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Recursive     map[int32]*Maps                    `protobuf:"bytes,24,rep,name=recursive,proto3" json:"recursive,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Maps) Reset() {
	*x = Maps{}
	mi := &file_abada_conformance_v1_json_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maps) ProtoMessage() {}

func (x *Maps) ProtoReflect() protoreflect.Message {
	mi := &file_abada_conformance_v1_json_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maps.ProtoReflect.Descriptor instead.
func (*Maps) Descriptor() ([]byte, []int) {
	return file_abada_conformance_v1_json_proto_rawDescGZIP(), []int{4}
}

func (x *Maps) GetI32() map[int32]string {
	if x != nil {
		return x.I32
	}
	return nil
}

func (x *Maps) GetI64() map[int64]string {
	if x != nil {
		return x.I64
	}
	return nil
}

func (x *Maps) GetU32() map[uint32]string {
	if x != nil {
		return x.U32
	}
	return nil
}

func (x *Maps) GetU64() map[uint64]string {
	if x != nil {
		return x.U64
	}
	return nil
}

func (x *Maps) GetS32() map[int32]string {
	if x != nil {
		return x.S32
	}
	return nil
}

func (x *Maps) GetS64() map[int64]string {
	if x != nil {
		return x.S64
	}
	return nil
}

func (x *Maps) GetFx32() map[uint32]string {
	if x != nil {
		return x.Fx32
	}
	return nil
}

func (x *Maps) GetFx64() map[uint64]string {
	if x != nil {
		return x.Fx64
	}
	return nil
}

func (x *Maps) GetSfx32() map[int32]string {
	if x != nil {
		return x.Sfx32
	}
	return nil
}

func (x *Maps) GetSfx64() map[int64]string {
	if x != nil {
		return x.Sfx64
	}
	return nil
}

func (x *Maps) GetFlag() map[bool]string {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *Maps) GetStr() map[string]string {
	if x != nil {
		return x.Str
	}
	return nil
}

func (x *Maps) GetByt() map[string][]byte {
	if x != nil {
		return x.Byt
	}
	return nil
}

func (x *Maps) GetColor() map[string]Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Maps) GetNested() map[string]*Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Maps) GetDbl() map[string]float64 {
	if x != nil {
		return x.Dbl
	}
	return nil
}

func (x *Maps) GetI64Value() map[string]int64 {
	if x != nil {
		return x.I64Value
	}
	return nil
}

func (x *Maps) GetValue() map[string]*structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Maps) GetTs() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Maps) GetStrWrapper() map[string]*wrapperspb.StringValue {
	if x != nil {
		return x.StrWrapper
	}
	return nil
}

func (x *Maps) GetFlt() map[string]float32 {
	if x != nil {
		return x.Flt
	}
	return nil
}

func (x *Maps) GetFlagValue() map[string]bool {
	if x != nil {
		return x.FlagValue
	}
	return nil
}

func (x *Maps) GetU32Value() map[string]uint32 {
	if x != nil {
		return x.U32Value
	}
	return nil
}

func (x *Maps) GetRecursive() map[int32]*Maps {
	if x != nil {
		return x.Recursive
	}
	return nil
}

type Oneofs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Oneofs_Str
	//	*Oneofs_I64
	//	*Oneofs_Color
	//	*Oneofs_Nested
	//	*Oneofs_Ts
	//	*Oneofs_Any
	//	*Oneofs_Value
	//	*Oneofs_Null
	//	*Oneofs_I32Wrapper
	//	*Oneofs_Byt
	//	*Oneofs_Empty
	//	*Oneofs_Dbl
	Kind  isOneofs_Kind `protobuf_oneof:"kind"`
	After string        `protobuf:"bytes,20,opt,name=after,proto3" json:"after,omitempty"`
	// Types that are valid to be assigned to Second:
	//
	//	*Oneofs_Flag
	//	*Oneofs_St
	Second        isOneofs_Second `protobuf_oneof:"second"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Oneofs) Reset() {
	*x = Oneofs{}
	mi := &file_abada_conformance_v1_json_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Oneofs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oneofs) ProtoMessage() {}

func (x *Oneofs) ProtoReflect() protoreflect.Message {
	mi := &file_abada_conformance_v1_json_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oneofs.ProtoReflect.Descriptor instead.
func (*Oneofs) Descriptor() ([]byte, []int) {
	return file_abada_conformance_v1_json_proto_rawDescGZIP(), []int{5}
}

func (x *Oneofs) GetKind() isOneofs_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Oneofs) GetStr() string {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Oneofs) GetI64() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_I64); ok {
			return x.I64
		}
	}
	return 0
}

func (x *Oneofs) GetColor() Color {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_Color); ok {
			return x.Color
		}
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Oneofs) GetNested() *Nested {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_Nested); ok {
			return x.Nested
		}
	}
	return nil
}

func (x *Oneofs) GetTs() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_Ts); ok {
			return x.Ts
		}
	}
	return nil
}

func (x *Oneofs) GetAny() *anypb.Any {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_Any); ok {
			return x.Any
		}
	}
	return nil
}

func (x *Oneofs) GetValue() *structpb.Value {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *Oneofs) GetNull() structpb.NullValue {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_Null); ok {
			return x.Null
		}
	}
	return structpb.NullValue(0)
}

func (x *Oneofs) GetI32Wrapper() *wrapperspb.Int32Value {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_I32Wrapper); ok {
			return x.I32Wrapper
		}
	}
	return nil
}

func (x *Oneofs) GetByt() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_Byt); ok {
			return x.Byt
		}
	}
	return nil
}

func (x *Oneofs) GetEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *Oneofs) GetDbl() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Oneofs_Dbl); ok {
			return x.Dbl
		}
	}
	return 0
}

func (x *Oneofs) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *Oneofs) GetSecond() isOneofs_Second {
	if x != nil {
		return x.Second
	}
	return nil
}

func (x *Oneofs) GetFlag() bool {
	if x != nil {
		if x, ok := x.Second.(*Oneofs_Flag); ok {
			return x.Flag
		}
	}
	return false
}

func (x *Oneofs) GetSt() *structpb.Struct {
	if x != nil {
		if x, ok := x.Second.(*Oneofs_St); ok {
			return x.St
		}
	}
	return nil
}

type isOneofs_Kind interface {
	isOneofs_Kind()
}

type Oneofs_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3,oneof"`
}

type Oneofs_I64 struct {
	I64 int64 `protobuf:"varint,2,opt,name=i64,proto3,oneof"`
}

type Oneofs_Color struct {
	Color Color `protobuf:"varint,3,opt,name=color,proto3,enum=abada.conformance.v1.Color,oneof"`
}

type Oneofs_Nested struct {
	Nested *Nested `protobuf:"bytes,4,opt,name=nested,proto3,oneof"`
}

type Oneofs_Ts struct {
	Ts *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ts,proto3,oneof"`
}

type Oneofs_Any struct {
	Any *anypb.Any `protobuf:"bytes,6,opt,name=any,proto3,oneof"`
}

type Oneofs_Value struct {
	Value *structpb.Value `protobuf:"bytes,7,opt,name=value,proto3,oneof"`
}

type Oneofs_Null struct {
	Null structpb.NullValue `protobuf:"varint,8,opt,name=null,proto3,enum=google.protobuf.NullValue,oneof"`
}

type Oneofs_I32Wrapper struct {
	I32Wrapper *wrapperspb.Int32Value `protobuf:"bytes,9,opt,name=i32_wrapper,json=i32Wrapper,proto3,oneof"`
}

type Oneofs_Byt struct {
	Byt []byte `protobuf:"bytes,10,opt,name=byt,proto3,oneof"`
}

type Oneofs_Empty struct {
	Empty *emptypb.Empty `protobuf:"bytes,11,opt,name=empty,proto3,oneof"`
}

type Oneofs_Dbl struct {
	Dbl float64 `protobuf:"fixed64,12,opt,name=dbl,proto3,oneof"`
}

func (*Oneofs_Str) isOneofs_Kind() {}

func (*Oneofs_I64) isOneofs_Kind() {}

func (*Oneofs_Color) isOneofs_Kind() {}

func (*Oneofs_Nested) isOneofs_Kind() {}

func (*Oneofs_Ts) isOneofs_Kind() {}

func (*Oneofs_Any) isOneofs_Kind() {}

func (*Oneofs_Value) isOneofs_Kind() {}

func (*Oneofs_Null) isOneofs_Kind() {}

func (*Oneofs_I32Wrapper) isOneofs_Kind() {}

func (*Oneofs_Byt) isOneofs_Kind() {}

func (*Oneofs_Empty) isOneofs_Kind() {}

func (*Oneofs_Dbl) isOneofs_Kind() {}

type isOneofs_Second interface {
	isOneofs_Second()
}

type Oneofs_Flag struct {
	Flag bool `protobuf:"varint,21,opt,name=flag,proto3,oneof"`
}

type Oneofs_St struct {
	St *structpb.Struct `protobuf:"bytes,22,opt,name=st,proto3,oneof"`
}

func (*Oneofs_Flag) isOneofs_Second() {}

func (*Oneofs_St) isOneofs_Second() {}

type WellKnown struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Any           *anypb.Any              `protobuf:"bytes,1,opt,name=any,proto3" json:"any,omitempty"`
	Ts            *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Dur           *durationpb.Duration    `protobuf:"bytes,3,opt,name=dur,proto3" json:"dur,omitempty"`
	Mask          *fieldmaskpb.FieldMask  `protobuf:"bytes,4,opt,name=mask,proto3" json:"mask,omitempty"`
	St            *structpb.Struct        `protobuf:"bytes,5,opt,name=st,proto3" json:"st,omitempty"`
	Value         *structpb.Value         `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	List          *structpb.ListValue     `protobuf:"bytes,7,opt,name=list,proto3" json:"list,omitempty"`
	Null          structpb.NullValue      `protobuf:"varint,8,opt,name=null,proto3,enum=google.protobuf.NullValue" json:"null,omitempty"`
	Empty         *emptypb.Empty          `protobuf:"bytes,9,opt,name=empty,proto3" json:"empty,omitempty"`
	BoolWrapper   *wrapperspb.BoolValue   `protobuf:"bytes,10,opt,name=bool_wrapper,json=boolWrapper,proto3" json:"bool_wrapper,omitempty"`
	I32Wrapper    *wrapperspb.Int32Value  `protobuf:"bytes,11,opt,name=i32_wrapper,json=i32Wrapper,proto3" json:"i32_wrapper,omitempty"`
	I64Wrapper    *wrapperspb.Int64Value  `protobuf:"bytes,12,opt,name=i64_wrapper,json=i64Wrapper,proto3" json:"i64_wrapper,omitempty"`
	U32Wrapper    *wrapperspb.UInt32Value `protobuf:"bytes,13,opt,name=u32_wrapper,json=u32Wrapper,proto3" json:"u32_wrapper,omitempty"`
	U64Wrapper    *wrapperspb.UInt64Value `protobuf:"bytes,14,opt,name=u64_wrapper,json=u64Wrapper,proto3" json:"u64_wrapper,omitempty"`
	FltWrapper    *wrapperspb.FloatValue  `protobuf:"bytes,15,opt,name=flt_wrapper,json=fltWrapper,proto3" json:"flt_wrapper,omitempty"`
	DblWrapper    *wrapperspb.DoubleValue `protobuf:"bytes,16,opt,name=dbl_wrapper,json=dblWrapper,proto3" json:"dbl_wrapper,omitempty"`
	StrWrapper    *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=str_wrapper,json=strWrapper,proto3" json:"str_wrapper,omitempty"`
	BytWrapper    *wrapperspb.BytesValue  `protobuf:"bytes,18,opt,name=byt_wrapper,json=bytWrapper,proto3" json:"byt_wrapper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WellKnown) Reset() {
	*x = WellKnown{}
	mi := &file_abada_conformance_v1_json_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WellKnown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WellKnown) ProtoMessage() {}

func (x *WellKnown) ProtoReflect() protoreflect.Message {
	mi := &file_abada_conformance_v1_json_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WellKnown.ProtoReflect.Descriptor instead.
func (*WellKnown) Descriptor() ([]byte, []int) {
	return file_abada_conformance_v1_json_proto_rawDescGZIP(), []int{6}
}

func (x *WellKnown) GetAny() *anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

func (x *WellKnown) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *WellKnown) GetDur() *durationpb.Duration {
	if x != nil {
		return x.Dur
	}
	return nil
}

func (x *WellKnown) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *WellKnown) GetSt() *structpb.Struct {
	if x != nil {
		return x.St
	}
	return nil
}

func (x *WellKnown) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WellKnown) GetList() *structpb.ListValue {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *WellKnown) GetNull() structpb.NullValue {
	if x != nil {
		return x.Null
	}
	return structpb.NullValue(0)
}

func (x *WellKnown) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

func (x *WellKnown) GetBoolWrapper() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolWrapper
	}
	return nil
}

func (x *WellKnown) GetI32Wrapper() *wrapperspb.Int32Value {
	if x != nil {
		return x.I32Wrapper
	}
	return nil
}

func (x *WellKnown) GetI64Wrapper() *wrapperspb.Int64Value {
	if x != nil {
		return x.I64Wrapper
	}
	return nil
}

func (x *WellKnown) GetU32Wrapper() *wrapperspb.UInt32Value {
	if x != nil {
		return x.U32Wrapper
	}
	return nil
}

func (x *WellKnown) GetU64Wrapper() *wrapperspb.UInt64Value {
	if x != nil {
		return x.U64Wrapper
	}
	return nil
}

func (x *WellKnown) GetFltWrapper() *wrapperspb.FloatValue {
	if x != nil {
		return x.FltWrapper
	}
	return nil
}

func (x *WellKnown) GetDblWrapper() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DblWrapper
	}
	return nil
}

func (x *WellKnown) GetStrWrapper() *wrapperspb.StringValue {
	if x != nil {
		return x.StrWrapper
	}
	return nil
}

func (x *WellKnown) GetBytWrapper() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytWrapper
	}
	return nil
}

var File_abada_conformance_v1_json_proto protoreflect.FileDescriptor

const file_abada_conformance_v1_json_proto_rawDesc = "" +
	"\n" +
	"\x1fabada/conformance/v1/json.proto\x12\x14abada.conformance.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"f\n" +
	"\x06Nested\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x05child\x18\x02 \x01(\v2\x1c.abada.conformance.v1.NestedR\x05child\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\"\xe3\x04\n" +
	"\aScalars\x127\n" +
	"\x18late_declared_low_number\x18c \x01(\tR\x15lateDeclaredLowNumber\x12\x10\n" +
	"\x03i32\x18\x01 \x01(\x05R\x03i32\x12\x10\n" +
	"\x03i64\x18\x02 \x01(\x03R\x03i64\x12\x10\n" +
	"\x03u32\x18\x03 \x01(\rR\x03u32\x12\x10\n" +
	"\x03u64\x18\x04 \x01(\x04R\x03u64\x12\x10\n" +
	"\x03s32\x18\x05 \x01(\x11R\x03s32\x12\x10\n" +
	"\x03s64\x18\x06 \x01(\x12R\x03s64\x12\x12\n" +
	"\x04fx32\x18\a \x01(\aR\x04fx32\x12\x12\n" +
	"\x04fx64\x18\b \x01(\x06R\x04fx64\x12\x14\n" +
	"\x05sfx32\x18\t \x01(\x0fR\x05sfx32\x12\x14\n" +
	"\x05sfx64\x18\n" +
	" \x01(\x10R\x05sfx64\x12\x10\n" +
	"\x03flt\x18\v \x01(\x02R\x03flt\x12\x10\n" +
	"\x03dbl\x18\f \x01(\x01R\x03dbl\x12\x12\n" +
	"\x04flag\x18\r \x01(\bR\x04flag\x12\x10\n" +
	"\x03str\x18\x0e \x01(\tR\x03str\x12\x10\n" +
	"\x03byt\x18\x0f \x01(\fR\x03byt\x121\n" +
	"\x05color\x18\x10 \x01(\x0e2\x1b.abada.conformance.v1.ColorR\x05color\x121\n" +
	"\x05alias\x18\x11 \x01(\x0e2\x1b.abada.conformance.v1.AliasR\x05alias\x12\x17\n" +
	"\x06custom\x18\x12 \x01(\tR\arenamed\x12&\n" +
	"\x0fsnake_case_name\x18\x13 \x01(\tR\rsnakeCaseName\x12\x17\n" +
	"\aname_1a\x18\x14 \x01(\tR\x06name1a\x12\r\n" +
	"\x02x_\x18\x15 \x01(\tR\x01x\x124\n" +
	"\x06nested\x18\x16 \x01(\v2\x1c.abada.conformance.v1.NestedR\x06nested\"\xa8\x05\n" +
	"\bRepeated\x12\x10\n" +
	"\x03i32\x18\x01 \x03(\x05R\x03i32\x12\x10\n" +
	"\x03i64\x18\x02 \x03(\x03R\x03i64\x12\x10\n" +
	"\x03u32\x18\x03 \x03(\rR\x03u32\x12\x10\n" +
	"\x03u64\x18\x04 \x03(\x04R\x03u64\x12\x10\n" +
	"\x03s32\x18\x05 \x03(\x11R\x03s32\x12\x10\n" +
	"\x03s64\x18\x06 \x03(\x12R\x03s64\x12\x12\n" +
	"\x04fx32\x18\a \x03(\aR\x04fx32\x12\x12\n" +
	"\x04fx64\x18\b \x03(\x06R\x04fx64\x12\x14\n" +
	"\x05sfx32\x18\t \x03(\x0fR\x05sfx32\x12\x14\n" +
	"\x05sfx64\x18\n" +
	" \x03(\x10R\x05sfx64\x12\x10\n" +
	"\x03flt\x18\v \x03(\x02R\x03flt\x12\x10\n" +
	"\x03dbl\x18\f \x03(\x01R\x03dbl\x12\x12\n" +
	"\x04flag\x18\r \x03(\bR\x04flag\x12\x10\n" +
	"\x03str\x18\x0e \x03(\tR\x03str\x12\x10\n" +
	"\x03byt\x18\x0f \x03(\fR\x03byt\x121\n" +
	"\x05color\x18\x10 \x03(\x0e2\x1b.abada.conformance.v1.ColorR\x05color\x124\n" +
	"\x06nested\x18\x11 \x03(\v2\x1c.abada.conformance.v1.NestedR\x06nested\x12*\n" +
	"\x02ts\x18\x12 \x03(\v2\x1a.google.protobuf.TimestampR\x02ts\x12&\n" +
	"\x03any\x18\x13 \x03(\v2\x14.google.protobuf.AnyR\x03any\x12,\n" +
	"\x05value\x18\x14 \x03(\v2\x16.google.protobuf.ValueR\x05value\x12<\n" +
	"\vi64_wrapper\x18\x15 \x03(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"i64Wrapper\x12.\n" +
	"\x04null\x18\x16 \x03(\x0e2\x1a.google.protobuf.NullValueR\x04null\x12'\n" +
	"\x02st\x18\x17 \x03(\v2\x17.google.protobuf.StructR\x02st\"\xe7\x02\n" +
	"\tOptionals\x12\x15\n" +
	"\x03i32\x18\x01 \x01(\x05H\x00R\x03i32\x88\x01\x01\x12\x15\n" +
	"\x03i64\x18\x02 \x01(\x03H\x01R\x03i64\x88\x01\x01\x12\x15\n" +
	"\x03u32\x18\x03 \x01(\rH\x02R\x03u32\x88\x01\x01\x12\x15\n" +
	"\x03u64\x18\x04 \x01(\x04H\x03R\x03u64\x88\x01\x01\x12\x15\n" +
	"\x03flt\x18\v \x01(\x02H\x04R\x03flt\x88\x01\x01\x12\x15\n" +
	"\x03dbl\x18\f \x01(\x01H\x05R\x03dbl\x88\x01\x01\x12\x17\n" +
	"\x04flag\x18\r \x01(\bH\x06R\x04flag\x88\x01\x01\x12\x15\n" +
	"\x03str\x18\x0e \x01(\tH\aR\x03str\x88\x01\x01\x12\x15\n" +
	"\x03byt\x18\x0f \x01(\fH\bR\x03byt\x88\x01\x01\x126\n" +
	"\x05color\x18\x10 \x01(\x0e2\x1b.abada.conformance.v1.ColorH\tR\x05color\x88\x01\x01B\x06\n" +
	"\x04_i32B\x06\n" +
	"\x04_i64B\x06\n" +
	"\x04_u32B\x06\n" +
	"\x04_u64B\x06\n" +
	"\x04_fltB\x06\n" +
	"\x04_dblB\a\n" +
	"\x05_flagB\x06\n" +
	"\x04_strB\x06\n" +
	"\x04_bytB\b\n" +
	"\x06_color\"\xc3\x17\n" +
	"\x04Maps\x125\n" +
	"\x03i32\x18\x01 \x03(\v2#.abada.conformance.v1.Maps.I32EntryR\x03i32\x125\n" +
	"\x03i64\x18\x02 \x03(\v2#.abada.conformance.v1.Maps.I64EntryR\x03i64\x125\n" +
	"\x03u32\x18\x03 \x03(\v2#.abada.conformance.v1.Maps.U32EntryR\x03u32\x125\n" +
	"\x03u64\x18\x04 \x03(\v2#.abada.conformance.v1.Maps.U64EntryR\x03u64\x125\n" +
	"\x03s32\x18\x05 \x03(\v2#.abada.conformance.v1.Maps.S32EntryR\x03s32\x125\n" +
	"\x03s64\x18\x06 \x03(\v2#.abada.conformance.v1.Maps.S64EntryR\x03s64\x128\n" +
	"\x04fx32\x18\a \x03(\v2$.abada.conformance.v1.Maps.Fx32EntryR\x04fx32\x128\n" +
	"\x04fx64\x18\b \x03(\v2$.abada.conformance.v1.Maps.Fx64EntryR\x04fx64\x12;\n" +
	"\x05sfx32\x18\t \x03(\v2%.abada.conformance.v1.Maps.Sfx32EntryR\x05sfx32\x12;\n" +
	"\x05sfx64\x18\n" +
	" \x03(\v2%.abada.conformance.v1.Maps.Sfx64EntryR\x05sfx64\x128\n" +
	"\x04flag\x18\v \x03(\v2$.abada.conformance.v1.Maps.FlagEntryR\x04flag\x125\n" +
	"\x03str\x18\f \x03(\v2#.abada.conformance.v1.Maps.StrEntryR\x03str\x125\n" +
	"\x03byt\x18\r \x03(\v2#.abada.conformance.v1.Maps.BytEntryR\x03byt\x12;\n" +
	"\x05color\x18\x0e \x03(\v2%.abada.conformance.v1.Maps.ColorEntryR\x05color\x12>\n" +
	"\x06nested\x18\x0f \x03(\v2&.abada.conformance.v1.Maps.NestedEntryR\x06nested\x125\n" +
	"\x03dbl\x18\x10 \x03(\v2#.abada.conformance.v1.Maps.DblEntryR\x03dbl\x12E\n" +
	"\ti64_value\x18\x11 \x03(\v2(.abada.conformance.v1.Maps.I64ValueEntryR\bi64Value\x12;\n" +
	"\x05value\x18\x12 \x03(\v2%.abada.conformance.v1.Maps.ValueEntryR\x05value\x122\n" +
	"\x02ts\x18\x13 \x03(\v2\".abada.conformance.v1.Maps.TsEntryR\x02ts\x12K\n" +
	"\vstr_wrapper\x18\x14 \x03(\v2*.abada.conformance.v1.Maps.StrWrapperEntryR\n" +
	"strWrapper\x125\n" +
	"\x03flt\x18\x15 \x03(\v2#.abada.conformance.v1.Maps.FltEntryR\x03flt\x12H\n" +
	"\n" +
	"flag_value\x18\x16 \x03(\v2).abada.conformance.v1.Maps.FlagValueEntryR\tflagValue\x12E\n" +
	"\tu32_value\x18\x17 \x03(\v2(.abada.conformance.v1.Maps.U32ValueEntryR\bu32Value\x12G\n" +
	"\trecursive\x18\x18 \x03(\v2).abada.conformance.v1.Maps.RecursiveEntryR\trecursive\x1a6\n" +
	"\bI32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bI64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bU32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bU64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bS32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x11R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bS64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x12R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tFx32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\aR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tFx64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x06R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"Sfx32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x0fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"Sfx64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x10R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tFlagEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bStrEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bBytEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1aU\n" +
	"\n" +
	"ColorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\x0e2\x1b.abada.conformance.v1.ColorR\x05value:\x028\x01\x1aW\n" +
	"\vNestedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.abada.conformance.v1.NestedR\x05value:\x028\x01\x1a6\n" +
	"\bDblEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a;\n" +
	"\rI64ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aP\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1aQ\n" +
	"\aTsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01\x1a[\n" +
	"\x0fStrWrapperEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05value:\x028\x01\x1a6\n" +
	"\bFltEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a<\n" +
	"\x0eFlagValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a;\n" +
	"\rU32ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aX\n" +
	"\x0eRecursiveEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.abada.conformance.v1.MapsR\x05value:\x028\x01\"\xd8\x04\n" +
	"\x06Oneofs\x12\x12\n" +
	"\x03str\x18\x01 \x01(\tH\x00R\x03str\x12\x12\n" +
	"\x03i64\x18\x02 \x01(\x03H\x00R\x03i64\x123\n" +
	"\x05color\x18\x03 \x01(\x0e2\x1b.abada.conformance.v1.ColorH\x00R\x05color\x126\n" +
	"\x06nested\x18\x04 \x01(\v2\x1c.abada.conformance.v1.NestedH\x00R\x06nested\x12,\n" +
	"\x02ts\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x02ts\x12(\n" +
	"\x03any\x18\x06 \x01(\v2\x14.google.protobuf.AnyH\x00R\x03any\x12.\n" +
	"\x05value\x18\a \x01(\v2\x16.google.protobuf.ValueH\x00R\x05value\x120\n" +
	"\x04null\x18\b \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\x04null\x12>\n" +
	"\vi32_wrapper\x18\t \x01(\v2\x1b.google.protobuf.Int32ValueH\x00R\n" +
	"i32Wrapper\x12\x12\n" +
	"\x03byt\x18\n" +
	" \x01(\fH\x00R\x03byt\x12.\n" +
	"\x05empty\x18\v \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05empty\x12\x12\n" +
	"\x03dbl\x18\f \x01(\x01H\x00R\x03dbl\x12\x14\n" +
	"\x05after\x18\x14 \x01(\tR\x05after\x12\x14\n" +
	"\x04flag\x18\x15 \x01(\bH\x01R\x04flag\x12)\n" +
	"\x02st\x18\x16 \x01(\v2\x17.google.protobuf.StructH\x01R\x02stB\x06\n" +
	"\x04kindB\b\n" +
	"\x06second\"\xd4\a\n" +
	"\tWellKnown\x12&\n" +
	"\x03any\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x03any\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12+\n" +
	"\x03dur\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03dur\x12.\n" +
	"\x04mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\x12'\n" +
	"\x02st\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x02st\x12,\n" +
	"\x05value\x18\x06 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12.\n" +
	"\x04list\x18\a \x01(\v2\x1a.google.protobuf.ListValueR\x04list\x12.\n" +
	"\x04null\x18\b \x01(\x0e2\x1a.google.protobuf.NullValueR\x04null\x12,\n" +
	"\x05empty\x18\t \x01(\v2\x16.google.protobuf.EmptyR\x05empty\x12=\n" +
	"\fbool_wrapper\x18\n" +
	" \x01(\v2\x1a.google.protobuf.BoolValueR\vboolWrapper\x12<\n" +
	"\vi32_wrapper\x18\v \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"i32Wrapper\x12<\n" +
	"\vi64_wrapper\x18\f \x01(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"i64Wrapper\x12=\n" +
	"\vu32_wrapper\x18\r \x01(\v2\x1c.google.protobuf.UInt32ValueR\n" +
	"u32Wrapper\x12=\n" +
	"\vu64_wrapper\x18\x0e \x01(\v2\x1c.google.protobuf.UInt64ValueR\n" +
	"u64Wrapper\x12<\n" +
	"\vflt_wrapper\x18\x0f \x01(\v2\x1b.google.protobuf.FloatValueR\n" +
	"fltWrapper\x12=\n" +
	"\vdbl_wrapper\x18\x10 \x01(\v2\x1c.google.protobuf.DoubleValueR\n" +
	"dblWrapper\x12=\n" +
	"\vstr_wrapper\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"strWrapper\x12<\n" +
	"\vbyt_wrapper\x18\x12 \x01(\v2\x1b.google.protobuf.BytesValueR\n" +
	"bytWrapper*[\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCOLOR_RED\x10\x01\x12\x0f\n" +
	"\vCOLOR_GREEN\x10\x02\x12\x1b\n" +
	"\x0eCOLOR_NEGATIVE\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*9\n" +
	"\x05Alias\x12\x0e\n" +
	"\n" +
	"ALIAS_ZERO\x10\x00\x12\r\n" +
	"\tALIAS_ONE\x10\x01\x12\r\n" +
	"\tALIAS_UNO\x10\x01\x1a\x02\x10\x01BPZNgithub.com/grpc-ecosystem/grpc-gateway/v2/internal/abadaoracle/abadapb;abadapbb\x06proto3"

var (
	file_abada_conformance_v1_json_proto_rawDescOnce sync.Once
	file_abada_conformance_v1_json_proto_rawDescData []byte
)

func file_abada_conformance_v1_json_proto_rawDescGZIP() []byte {
	file_abada_conformance_v1_json_proto_rawDescOnce.Do(func() {
		file_abada_conformance_v1_json_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abada_conformance_v1_json_proto_rawDesc), len(file_abada_conformance_v1_json_proto_rawDesc)))
	})
	return file_abada_conformance_v1_json_proto_rawDescData
}

var file_abada_conformance_v1_json_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_abada_conformance_v1_json_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_abada_conformance_v1_json_proto_goTypes = []any{
	(Color)(0),                     // 0: abada.conformance.v1.Color
	(Alias)(0),                     // 1: abada.conformance.v1.Alias
	(*Nested)(nil),                 // 2: abada.conformance.v1.Nested
	(*Scalars)(nil),                // 3: abada.conformance.v1.Scalars
	(*Repeated)(nil),               // 4: abada.conformance.v1.Repeated
	(*Optionals)(nil),              // 5: abada.conformance.v1.Optionals
	(*Maps)(nil),                   // 6: abada.conformance.v1.Maps
	(*Oneofs)(nil),                 // 7: abada.conformance.v1.Oneofs
	(*WellKnown)(nil),              // 8: abada.conformance.v1.WellKnown
	nil,                            // 9: abada.conformance.v1.Maps.I32Entry
	nil,                            // 10: abada.conformance.v1.Maps.I64Entry
	nil,                            // 11: abada.conformance.v1.Maps.U32Entry
	nil,                            // 12: abada.conformance.v1.Maps.U64Entry
	nil,                            // 13: abada.conformance.v1.Maps.S32Entry
	nil,                            // 14: abada.conformance.v1.Maps.S64Entry
	nil,                            // 15: abada.conformance.v1.Maps.Fx32Entry
	nil,                            // 16: abada.conformance.v1.Maps.Fx64Entry
	nil,                            // 17: abada.conformance.v1.Maps.Sfx32Entry
	nil,                            // 18: abada.conformance.v1.Maps.Sfx64Entry
	nil,                            // 19: abada.conformance.v1.Maps.FlagEntry
	nil,                            // 20: abada.conformance.v1.Maps.StrEntry
	nil,                            // 21: abada.conformance.v1.Maps.BytEntry
	nil,                            // 22: abada.conformance.v1.Maps.ColorEntry
	nil,                            // 23: abada.conformance.v1.Maps.NestedEntry
	nil,                            // 24: abada.conformance.v1.Maps.DblEntry
	nil,                            // 25: abada.conformance.v1.Maps.I64ValueEntry
	nil,                            // 26: abada.conformance.v1.Maps.ValueEntry
	nil,                            // 27: abada.conformance.v1.Maps.TsEntry
	nil,                            // 28: abada.conformance.v1.Maps.StrWrapperEntry
	nil,                            // 29: abada.conformance.v1.Maps.FltEntry
	nil,                            // 30: abada.conformance.v1.Maps.FlagValueEntry
	nil,                            // 31: abada.conformance.v1.Maps.U32ValueEntry
	nil,                            // 32: abada.conformance.v1.Maps.RecursiveEntry
	(*timestamppb.Timestamp)(nil),  // 33: google.protobuf.Timestamp
	(*anypb.Any)(nil),              // 34: google.protobuf.Any
	(*structpb.Value)(nil),         // 35: google.protobuf.Value
	(*wrapperspb.Int64Value)(nil),  // 36: google.protobuf.Int64Value
	(structpb.NullValue)(0),        // 37: google.protobuf.NullValue
	(*structpb.Struct)(nil),        // 38: google.protobuf.Struct
	(*wrapperspb.Int32Value)(nil),  // 39: google.protobuf.Int32Value
	(*emptypb.Empty)(nil),          // 40: google.protobuf.Empty
	(*durationpb.Duration)(nil),    // 41: google.protobuf.Duration
	(*fieldmaskpb.FieldMask)(nil),  // 42: google.protobuf.FieldMask
	(*structpb.ListValue)(nil),     // 43: google.protobuf.ListValue
	(*wrapperspb.BoolValue)(nil),   // 44: google.protobuf.BoolValue
	(*wrapperspb.UInt32Value)(nil), // 45: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 46: google.protobuf.UInt64Value
	(*wrapperspb.FloatValue)(nil),  // 47: google.protobuf.FloatValue
	(*wrapperspb.DoubleValue)(nil), // 48: google.protobuf.DoubleValue
	(*wrapperspb.StringValue)(nil), // 49: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 50: google.protobuf.BytesValue
}
var file_abada_conformance_v1_json_proto_depIdxs = []int32{
	2,  // 0: abada.conformance.v1.Nested.child:type_name -> abada.conformance.v1.Nested
	0,  // 1: abada.conformance.v1.Scalars.color:type_name -> abada.conformance.v1.Color
	1,  // 2: abada.conformance.v1.Scalars.alias:type_name -> abada.conformance.v1.Alias
	2,  // 3: abada.conformance.v1.Scalars.nested:type_name -> abada.conformance.v1.Nested
	0,  // 4: abada.conformance.v1.Repeated.color:type_name -> abada.conformance.v1.Color
	2,  // 5: abada.conformance.v1.Repeated.nested:type_name -> abada.conformance.v1.Nested
	33, // 6: abada.conformance.v1.Repeated.ts:type_name -> google.protobuf.Timestamp
	34, // 7: abada.conformance.v1.Repeated.any:type_name -> google.protobuf.Any
	35, // 8: abada.conformance.v1.Repeated.value:type_name -> google.protobuf.Value
	36, // 9: abada.conformance.v1.Repeated.i64_wrapper:type_name -> google.protobuf.Int64Value
	37, // 10: abada.conformance.v1.Repeated.null:type_name -> google.protobuf.NullValue
	38, // 11: abada.conformance.v1.Repeated.st:type_name -> google.protobuf.Struct
	0,  // 12: abada.conformance.v1.Optionals.color:type_name -> abada.conformance.v1.Color
	9,  // 13: abada.conformance.v1.Maps.i32:type_name -> abada.conformance.v1.Maps.I32Entry
	10, // 14: abada.conformance.v1.Maps.i64:type_name -> abada.conformance.v1.Maps.I64Entry
	11, // 15: abada.conformance.v1.Maps.u32:type_name -> abada.conformance.v1.Maps.U32Entry
	12, // 16: abada.conformance.v1.Maps.u64:type_name -> abada.conformance.v1.Maps.U64Entry
	13, // 17: abada.conformance.v1.Maps.s32:type_name -> abada.conformance.v1.Maps.S32Entry
	14, // 18: abada.conformance.v1.Maps.s64:type_name -> abada.conformance.v1.Maps.S64Entry
	15, // 19: abada.conformance.v1.Maps.fx32:type_name -> abada.conformance.v1.Maps.Fx32Entry
	16, // 20: abada.conformance.v1.Maps.fx64:type_name -> abada.conformance.v1.Maps.Fx64Entry
	17, // 21: abada.conformance.v1.Maps.sfx32:type_name -> abada.conformance.v1.Maps.Sfx32Entry
	18, // 22: abada.conformance.v1.Maps.sfx64:type_name -> abada.conformance.v1.Maps.Sfx64Entry
	19, // 23: abada.conformance.v1.Maps.flag:type_name -> abada.conformance.v1.Maps.FlagEntry
	20, // 24: abada.conformance.v1.Maps.str:type_name -> abada.conformance.v1.Maps.StrEntry
	21, // 25: abada.conformance.v1.Maps.byt:type_name -> abada.conformance.v1.Maps.BytEntry
	22, // 26: abada.conformance.v1.Maps.color:type_name -> abada.conformance.v1.Maps.ColorEntry
	23, // 27: abada.conformance.v1.Maps.nested:type_name -> abada.conformance.v1.Maps.NestedEntry
	24, // 28: abada.conformance.v1.Maps.dbl:type_name -> abada.conformance.v1.Maps.DblEntry
	25, // 29: abada.conformance.v1.Maps.i64_value:type_name -> abada.conformance.v1.Maps.I64ValueEntry
	26, // 30: abada.conformance.v1.Maps.value:type_name -> abada.conformance.v1.Maps.ValueEntry
	27, // 31: abada.conformance.v1.Maps.ts:type_name -> abada.conformance.v1.Maps.TsEntry
	28, // 32: abada.conformance.v1.Maps.str_wrapper:type_name -> abada.conformance.v1.Maps.StrWrapperEntry
	29, // 33: abada.conformance.v1.Maps.flt:type_name -> abada.conformance.v1.Maps.FltEntry
	30, // 34: abada.conformance.v1.Maps.flag_value:type_name -> abada.conformance.v1.Maps.FlagValueEntry
	31, // 35: abada.conformance.v1.Maps.u32_value:type_name -> abada.conformance.v1.Maps.U32ValueEntry
	32, // 36: abada.conformance.v1.Maps.recursive:type_name -> abada.conformance.v1.Maps.RecursiveEntry
	0,  // 37: abada.conformance.v1.Oneofs.color:type_name -> abada.conformance.v1.Color
	2,  // 38: abada.conformance.v1.Oneofs.nested:type_name -> abada.conformance.v1.Nested
	33, // 39: abada.conformance.v1.Oneofs.ts:type_name -> google.protobuf.Timestamp
	34, // 40: abada.conformance.v1.Oneofs.any:type_name -> google.protobuf.Any
	35, // 41: abada.conformance.v1.Oneofs.value:type_name -> google.protobuf.Value
	37, // 42: abada.conformance.v1.Oneofs.null:type_name -> google.protobuf.NullValue
	39, // 43: abada.conformance.v1.Oneofs.i32_wrapper:type_name -> google.protobuf.Int32Value
	40, // 44: abada.conformance.v1.Oneofs.empty:type_name -> google.protobuf.Empty
	38, // 45: abada.conformance.v1.Oneofs.st:type_name -> google.protobuf.Struct
	34, // 46: abada.conformance.v1.WellKnown.any:type_name -> google.protobuf.Any
	33, // 47: abada.conformance.v1.WellKnown.ts:type_name -> google.protobuf.Timestamp
	41, // 48: abada.conformance.v1.WellKnown.dur:type_name -> google.protobuf.Duration
	42, // 49: abada.conformance.v1.WellKnown.mask:type_name -> google.protobuf.FieldMask
	38, // 50: abada.conformance.v1.WellKnown.st:type_name -> google.protobuf.Struct
	35, // 51: abada.conformance.v1.WellKnown.value:type_name -> google.protobuf.Value
	43, // 52: abada.conformance.v1.WellKnown.list:type_name -> google.protobuf.ListValue
	37, // 53: abada.conformance.v1.WellKnown.null:type_name -> google.protobuf.NullValue
	40, // 54: abada.conformance.v1.WellKnown.empty:type_name -> google.protobuf.Empty
	44, // 55: abada.conformance.v1.WellKnown.bool_wrapper:type_name -> google.protobuf.BoolValue
	39, // 56: abada.conformance.v1.WellKnown.i32_wrapper:type_name -> google.protobuf.Int32Value
	36, // 57: abada.conformance.v1.WellKnown.i64_wrapper:type_name -> google.protobuf.Int64Value
	45, // 58: abada.conformance.v1.WellKnown.u32_wrapper:type_name -> google.protobuf.UInt32Value
	46, // 59: abada.conformance.v1.WellKnown.u64_wrapper:type_name -> google.protobuf.UInt64Value
	47, // 60: abada.conformance.v1.WellKnown.flt_wrapper:type_name -> google.protobuf.FloatValue
	48, // 61: abada.conformance.v1.WellKnown.dbl_wrapper:type_name -> google.protobuf.DoubleValue
	49, // 62: abada.conformance.v1.WellKnown.str_wrapper:type_name -> google.protobuf.StringValue
	50, // 63: abada.conformance.v1.WellKnown.byt_wrapper:type_name -> google.protobuf.BytesValue
	0,  // 64: abada.conformance.v1.Maps.ColorEntry.value:type_name -> abada.conformance.v1.Color
	2,  // 65: abada.conformance.v1.Maps.NestedEntry.value:type_name -> abada.conformance.v1.Nested
	35, // 66: abada.conformance.v1.Maps.ValueEntry.value:type_name -> google.protobuf.Value
	33, // 67: abada.conformance.v1.Maps.TsEntry.value:type_name -> google.protobuf.Timestamp
	49, // 68: abada.conformance.v1.Maps.StrWrapperEntry.value:type_name -> google.protobuf.StringValue
	6,  // 69: abada.conformance.v1.Maps.RecursiveEntry.value:type_name -> abada.conformance.v1.Maps
	70, // [70:70] is the sub-list for method output_type
	70, // [70:70] is the sub-list for method input_type
	70, // [70:70] is the sub-list for extension type_name
	70, // [70:70] is the sub-list for extension extendee
	0,  // [0:70] is the sub-list for field type_name
}

func init() { file_abada_conformance_v1_json_proto_init() }
func file_abada_conformance_v1_json_proto_init() {
	if File_abada_conformance_v1_json_proto != nil {
		return
	}
	file_abada_conformance_v1_json_proto_msgTypes[3].OneofWrappers = []any{}
	file_abada_conformance_v1_json_proto_msgTypes[5].OneofWrappers = []any{
		(*Oneofs_Str)(nil),
		(*Oneofs_I64)(nil),
		(*Oneofs_Color)(nil),
		(*Oneofs_Nested)(nil),
		(*Oneofs_Ts)(nil),
		(*Oneofs_Any)(nil),
		(*Oneofs_Value)(nil),
		(*Oneofs_Null)(nil),
		(*Oneofs_I32Wrapper)(nil),
		(*Oneofs_Byt)(nil),
		(*Oneofs_Empty)(nil),
		(*Oneofs_Dbl)(nil),
		(*Oneofs_Flag)(nil),
		(*Oneofs_St)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abada_conformance_v1_json_proto_rawDesc), len(file_abada_conformance_v1_json_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abada_conformance_v1_json_proto_goTypes,
		DependencyIndexes: file_abada_conformance_v1_json_proto_depIdxs,
		EnumInfos:         file_abada_conformance_v1_json_proto_enumTypes,
		MessageInfos:      file_abada_conformance_v1_json_proto_msgTypes,
	}.Build()
	File_abada_conformance_v1_json_proto = out.File
	file_abada_conformance_v1_json_proto_goTypes = nil
	file_abada_conformance_v1_json_proto_depIdxs = nil
}
