// proto2 shapes for the JSON conformance vectors: explicit presence on
// scalars, defaults, required fields and extensions.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: abada/conformance/v1/json_proto2.proto

package abadapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proto2 struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	I32             *int32                     `protobuf:"varint,1,opt,name=i32,def=7" json:"i32,omitempty"`
	Str             *string                    `protobuf:"bytes,2,opt,name=str,def=x" json:"str,omitempty"`
	Inner           *Proto2Required            `protobuf:"bytes,3,opt,name=inner" json:"inner,omitempty"`
	Items           []*Proto2Required          `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	ByName          map[string]*Proto2Required `protobuf:"bytes,5,rep,name=by_name,json=byName" json:"by_name,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Byt             []byte                     `protobuf:"bytes,6,opt,name=byt" json:"byt,omitempty"`
	extensionFields protoimpl.ExtensionFields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Default values for Proto2 fields.
const (
	Default_Proto2_I32 = int32(7)
	Default_Proto2_Str = string("x")
)

func (x *Proto2) Reset() {
	*x = Proto2{}
	mi := &file_abada_conformance_v1_json_proto2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto2) ProtoMessage() {}

func (x *Proto2) ProtoReflect() protoreflect.Message {
	mi := &file_abada_conformance_v1_json_proto2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto2.ProtoReflect.Descriptor instead.
func (*Proto2) Descriptor() ([]byte, []int) {
	return file_abada_conformance_v1_json_proto2_proto_rawDescGZIP(), []int{0}
}

func (x *Proto2) GetI32() int32 {
	if x != nil && x.I32 != nil {
		return *x.I32
	}
	return Default_Proto2_I32
}

func (x *Proto2) GetStr() string {
	if x != nil && x.Str != nil {
		return *x.Str
	}
	return Default_Proto2_Str
}

func (x *Proto2) GetInner() *Proto2Required {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *Proto2) GetItems() []*Proto2Required {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Proto2) GetByName() map[string]*Proto2Required {
	if x != nil {
		return x.ByName
	}
	return nil
}

func (x *Proto2) GetByt() []byte {
	if x != nil {
		return x.Byt
	}
	return nil
}

type Proto2Required struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	N             *int32                 `protobuf:"varint,2,opt,name=n" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proto2Required) Reset() {
	*x = Proto2Required{}
	mi := &file_abada_conformance_v1_json_proto2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto2Required) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto2Required) ProtoMessage() {}

func (x *Proto2Required) ProtoReflect() protoreflect.Message {
	mi := &file_abada_conformance_v1_json_proto2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto2Required.ProtoReflect.Descriptor instead.
func (*Proto2Required) Descriptor() ([]byte, []int) {
	return file_abada_conformance_v1_json_proto2_proto_rawDescGZIP(), []int{1}
}

func (x *Proto2Required) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Proto2Required) GetN() int32 {
	if x != nil && x.N != nil {
		return *x.N
	}
	return 0
}

var file_abada_conformance_v1_json_proto2_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*Proto2)(nil),
		ExtensionType: (*string)(nil),
		Field:         100,
		Name:          "abada.conformance.v1.ext_str",
		Tag:           "bytes,100,opt,name=ext_str",
		Filename:      "abada/conformance/v1/json_proto2.proto",
	},
	{
		ExtendedType:  (*Proto2)(nil),
		ExtensionType: ([]int32)(nil),
		Field:         101,
		Name:          "abada.conformance.v1.ext_i32",
		Tag:           "varint,101,rep,name=ext_i32",
		Filename:      "abada/conformance/v1/json_proto2.proto",
	},
	{
		ExtendedType:  (*Proto2)(nil),
		ExtensionType: (*Proto2Required)(nil),
		Field:         102,
		Name:          "abada.conformance.v1.ext_msg",
		Tag:           "bytes,102,opt,name=ext_msg",
		Filename:      "abada/conformance/v1/json_proto2.proto",
	},
}

// Extension fields to Proto2.
var (
	// optional string ext_str = 100;
	E_ExtStr = &file_abada_conformance_v1_json_proto2_proto_extTypes[0]
	// repeated int32 ext_i32 = 101;
	E_ExtI32 = &file_abada_conformance_v1_json_proto2_proto_extTypes[1]
	// optional abada.conformance.v1.Proto2Required ext_msg = 102;
	E_ExtMsg = &file_abada_conformance_v1_json_proto2_proto_extTypes[2]
)

var File_abada_conformance_v1_json_proto2_proto protoreflect.FileDescriptor

const file_abada_conformance_v1_json_proto2_proto_rawDesc = "" +
	"\n" +
	"&abada/conformance/v1/json_proto2.proto\x12\x14abada.conformance.v1\"\xe7\x02\n" +
	"\x06Proto2\x12\x13\n" +
	"\x03i32\x18\x01 \x01(\x05:\x017R\x03i32\x12\x13\n" +
	"\x03str\x18\x02 \x01(\t:\x01xR\x03str\x12:\n" +
	"\x05inner\x18\x03 \x01(\v2$.abada.conformance.v1.Proto2RequiredR\x05inner\x12:\n" +
	"\x05items\x18\x04 \x03(\v2$.abada.conformance.v1.Proto2RequiredR\x05items\x12A\n" +
	"\aby_name\x18\x05 \x03(\v2(.abada.conformance.v1.Proto2.ByNameEntryR\x06byName\x12\x10\n" +
	"\x03byt\x18\x06 \x01(\fR\x03byt\x1a_\n" +
	"\vByNameEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.abada.conformance.v1.Proto2RequiredR\x05value:\x028\x01*\x05\bd\x10\xc8\x01\".\n" +
	"\x0eProto2Required\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\tR\x02id\x12\f\n" +
	"\x01n\x18\x02 \x01(\x05R\x01n:5\n" +
	"\aext_str\x12\x1c.abada.conformance.v1.Proto2\x18d \x01(\tR\x06extStr:5\n" +
	"\aext_i32\x12\x1c.abada.conformance.v1.Proto2\x18e \x03(\x05R\x06extI32:[\n" +
	"\aext_msg\x12\x1c.abada.conformance.v1.Proto2\x18f \x01(\v2$.abada.conformance.v1.Proto2RequiredR\x06extMsgBPZNgithub.com/grpc-ecosystem/grpc-gateway/v2/internal/abadaoracle/abadapb;abadapb"

var (
	file_abada_conformance_v1_json_proto2_proto_rawDescOnce sync.Once
	file_abada_conformance_v1_json_proto2_proto_rawDescData []byte
)

func file_abada_conformance_v1_json_proto2_proto_rawDescGZIP() []byte {
	file_abada_conformance_v1_json_proto2_proto_rawDescOnce.Do(func() {
		file_abada_conformance_v1_json_proto2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_abada_conformance_v1_json_proto2_proto_rawDesc), len(file_abada_conformance_v1_json_proto2_proto_rawDesc)))
	})
	return file_abada_conformance_v1_json_proto2_proto_rawDescData
}

var file_abada_conformance_v1_json_proto2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_abada_conformance_v1_json_proto2_proto_goTypes = []any{
	(*Proto2)(nil),         // 0: abada.conformance.v1.Proto2
	(*Proto2Required)(nil), // 1: abada.conformance.v1.Proto2Required
	nil,                    // 2: abada.conformance.v1.Proto2.ByNameEntry
}
var file_abada_conformance_v1_json_proto2_proto_depIdxs = []int32{
	1, // 0: abada.conformance.v1.Proto2.inner:type_name -> abada.conformance.v1.Proto2Required
	1, // 1: abada.conformance.v1.Proto2.items:type_name -> abada.conformance.v1.Proto2Required
	2, // 2: abada.conformance.v1.Proto2.by_name:type_name -> abada.conformance.v1.Proto2.ByNameEntry
	1, // 3: abada.conformance.v1.Proto2.ByNameEntry.value:type_name -> abada.conformance.v1.Proto2Required
	0, // 4: abada.conformance.v1.ext_str:extendee -> abada.conformance.v1.Proto2
	0, // 5: abada.conformance.v1.ext_i32:extendee -> abada.conformance.v1.Proto2
	0, // 6: abada.conformance.v1.ext_msg:extendee -> abada.conformance.v1.Proto2
	1, // 7: abada.conformance.v1.ext_msg:type_name -> abada.conformance.v1.Proto2Required
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	7, // [7:8] is the sub-list for extension type_name
	4, // [4:7] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_abada_conformance_v1_json_proto2_proto_init() }
func file_abada_conformance_v1_json_proto2_proto_init() {
	if File_abada_conformance_v1_json_proto2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_abada_conformance_v1_json_proto2_proto_rawDesc), len(file_abada_conformance_v1_json_proto2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_abada_conformance_v1_json_proto2_proto_goTypes,
		DependencyIndexes: file_abada_conformance_v1_json_proto2_proto_depIdxs,
		MessageInfos:      file_abada_conformance_v1_json_proto2_proto_msgTypes,
		ExtensionInfos:    file_abada_conformance_v1_json_proto2_proto_extTypes,
	}.Build()
	File_abada_conformance_v1_json_proto2_proto = out.File
	file_abada_conformance_v1_json_proto2_proto_goTypes = nil
	file_abada_conformance_v1_json_proto2_proto_depIdxs = nil
}
