#!/usr/bin/env bash
# Regenerates conformance/vectors/*.json by running grpc-gateway itself over
# conformance/cases/*.json. With --check, fails if the committed vectors differ
# from what grpc-gateway answers today.
set -euo pipefail

GATEWAY_TAG="${GATEWAY_TAG:-v2.27.3}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="${ABADA_REF_DIR:-$HOME/.cache/abada-ref}/grpc-gateway-$GATEWAY_TAG"

if [ ! -d "$WORK" ]; then
  git clone --quiet --depth 1 --branch "$GATEWAY_TAG" \
    https://github.com/grpc-ecosystem/grpc-gateway.git "$WORK"
fi
# The checkout is shared between runs and branches: start from an empty oracle
# directory, or a file removed or renamed here keeps compiling from the cache.
rm -rf "$WORK/internal/abadaoracle"
mkdir -p "$WORK/internal/abadaoracle"
cp "$ROOT"/conformance/oracle/*.go "$WORK/internal/abadaoracle/"
# Go types of conformance/protos, generated by conformance/protos/generate.sh.
cp -r "$ROOT"/conformance/oracle/abadapb "$WORK/internal/abadaoracle/"

# Test protos: conformance/protos/<pkg path>/*.proto compile into
# conformance/contracts/<pkg with dashes>.binpb, so they are routed and
# measured like a real contract. google/api comes from the delonix contract's
# set, google/protobuf from protoc's include directory. The binary is
# committed; --check fails if the .proto and the .binpb disagree.
PROTOC="${PROTOC:-protoc}"
PROTOC_INCLUDE="${PROTOC_INCLUDE:-$(dirname "$(command -v "$PROTOC")")/../include}"
for pdir in "$ROOT"/conformance/protos/abada/conformance/request/v1; do
  [ -d "$pdir" ] || continue
  rel="${pdir#"$ROOT"/conformance/protos/}"
  pname="$(echo "$rel" | tr '/' '-')"
  ptmp="$(mktemp "$ROOT/conformance/contracts/.$pname.XXXXXX")"
  (cd "$ROOT/conformance/protos" && "$PROTOC" --include_imports \
    --descriptor_set_in="$ROOT/conformance/contracts/delonix-node-v1.binpb" \
    -I . -I "$PROTOC_INCLUDE" -o "$ptmp" "$rel"/*.proto)
  pout="$ROOT/conformance/contracts/$pname.binpb"
  if [ "${1:-}" = "--check" ]; then
    if ! cmp -s "$ptmp" "$pout"; then
      rm -f "$ptmp"
      echo "$pout is stale: run scripts/regen-vectors.sh ($("$PROTOC" --version))" >&2
      exit 1
    fi
    rm -f "$ptmp"
  else
    mv "$ptmp" "$pout"
    echo "wrote $pout"
  fi
done

out="$ROOT/conformance/vectors/path.json"
tmp="$(mktemp "$ROOT/conformance/vectors/.path.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
(cd "$WORK" && ABADA_GENERATOR="grpc-gateway $GATEWAY_TAG, $(go version | cut -d' ' -f3)" \
  go run ./internal/abadaoracle) < "$ROOT/conformance/cases/path.json" > "$tmp"

# Real contracts: conformance/contracts/<name>.binpb, with <name>.source naming
# where the descriptor set came from.
for binpb in "$ROOT"/conformance/contracts/*.binpb; do
  [ -e "$binpb" ] || continue
  name="$(basename "$binpb" .binpb)"
  ctmp="$(mktemp "$ROOT/conformance/vectors/.$name.XXXXXX")"
  (cd "$WORK" && ABADA_GENERATOR="grpc-gateway $GATEWAY_TAG, $(go version | cut -d' ' -f3)" \
    go run ./internal/abadaoracle contract "$binpb" "$(cat "$ROOT/conformance/contracts/$name.source")") > "$ctmp"
  cout="$ROOT/conformance/vectors/contract-$name.json"
  if [ "${1:-}" = "--check" ]; then
    if ! diff <(grep -v '"generator"' "$cout") <(grep -v '"generator"' "$ctmp") > /dev/null; then
      rm -f "$ctmp"
      echo "$cout is stale: run scripts/regen-vectors.sh" >&2
      exit 1
    fi
    rm -f "$ctmp"
  else
    mv "$ctmp" "$cout"
    echo "wrote $cout"
  fi
done

# Errors: DefaultHTTPErrorHandler and the routing errors, over a real
# net/http server.
etmp="$(mktemp "$ROOT/conformance/vectors/.errors.XXXXXX")"
(cd "$WORK" && ABADA_GENERATOR="grpc-gateway $GATEWAY_TAG, $(go version | cut -d' ' -f3)" \
  go run ./internal/abadaoracle errors) < "$ROOT/conformance/cases/errors.json" > "$etmp"
eout="$ROOT/conformance/vectors/errors.json"
if [ "${1:-}" = "--check" ]; then
  if ! diff <(grep -v '"generator"' "$eout") <(grep -v '"generator"' "$etmp") > /dev/null; then
    rm -f "$etmp"
    echo "$eout is stale: run scripts/regen-vectors.sh" >&2
    exit 1
  fi
  rm -f "$etmp"
else
  mv "$etmp" "$eout"
  echo "wrote $eout"
fi

# JSON transcoding: conformance/cases/json-<name>.json holds bodies for the
# messages of contracts/<name>.binpb, or of protos/<name>.binpb (the protos
# written for the conformance suite); the vectors are what grpc-gateway's
# default marshaler accepts and answers for each.
for jcases in "$ROOT"/conformance/cases/json-*.json; do
  [ -e "$jcases" ] || continue
  name="$(basename "$jcases" .json)"
  name="${name#json-}"
  if [ -e "$ROOT/conformance/contracts/$name.binpb" ]; then
    binpb="$ROOT/conformance/contracts/$name.binpb"
    source="$(cat "$ROOT/conformance/contracts/$name.source")"
  else
    binpb="$ROOT/conformance/protos/$name.binpb"
    source="conformance/protos (conformance/protos/generate.sh)"
  fi
  jtmp="$(mktemp "$ROOT/conformance/vectors/.json-$name.XXXXXX")"
  (cd "$WORK" && ABADA_GENERATOR="grpc-gateway $GATEWAY_TAG, $(go version | cut -d' ' -f3)" \
    go run ./internal/abadaoracle json "$binpb" "$source") \
    < "$jcases" > "$jtmp"
  jout="$ROOT/conformance/vectors/json-$name.json"
  if [ "${1:-}" = "--check" ]; then
    if ! diff <(grep -v '"generator"' "$jout") <(grep -v '"generator"' "$jtmp") > /dev/null; then
      rm -f "$jtmp"
      echo "$jout is stale: run scripts/regen-vectors.sh" >&2
      exit 1
    fi
    rm -f "$jtmp"
  else
    mv "$jtmp" "$jout"
    echo "wrote $jout"
  fi
done

# Requests: what the code protoc-gen-grpc-gateway generates puts in the gRPC
# request for an HTTP request. The generated Go code is not committed: it is
# produced here, in the cache, from each contract with the plugins at pinned
# versions (protoc-gen-go from grpc-gateway's go.mod, protoc-gen-grpc-gateway
# from the checkout itself), then conformance/cases/request-<name>.json is
# replayed through it.
PROTOC_GEN_GO_GRPC_VERSION="${PROTOC_GEN_GO_GRPC_VERSION:-v1.5.1}"
BIN="$(dirname "$WORK")/bin"
mkdir -p "$BIN" "$WORK/internal/abadaoracle/e2e/protogen"
cp "$ROOT"/conformance/oracle/e2e/*.go "$WORK/internal/abadaoracle/e2e/"
cp "$ROOT"/conformance/oracle/e2e/protogen/*.go "$WORK/internal/abadaoracle/e2e/protogen/"
(cd "$WORK" && go build -o "$BIN/protoc-gen-grpc-gateway-$GATEWAY_TAG" ./protoc-gen-grpc-gateway \
  && go build -o "$BIN/protoc-gen-go-$GATEWAY_TAG" google.golang.org/protobuf/cmd/protoc-gen-go)
if [ ! -x "$BIN/protoc-gen-go-grpc-$PROTOC_GEN_GO_GRPC_VERSION" ]; then
  gtmp="$(mktemp -d "$BIN/.go-grpc.XXXXXX")"
  GOBIN="$gtmp" go install "google.golang.org/grpc/cmd/protoc-gen-go-grpc@$PROTOC_GEN_GO_GRPC_VERSION"
  mv "$gtmp/protoc-gen-go-grpc" "$BIN/protoc-gen-go-grpc-$PROTOC_GEN_GO_GRPC_VERSION"
  rmdir "$gtmp"
fi
for binpb in "$ROOT"/conformance/contracts/*.binpb; do
  [ -e "$binpb" ] || continue
  name="$(basename "$binpb" .binpb)"
  (cd "$WORK" && go run ./internal/abadaoracle/e2e/protogen -set "$binpb" \
    -importpath "github.com/grpc-ecosystem/grpc-gateway/v2/internal/abadaoracle/e2e/gen/$(echo "$name" | tr -d -)" \
    -module github.com/grpc-ecosystem/grpc-gateway/v2 -out . \
    -plugin "$BIN/protoc-gen-go-$GATEWAY_TAG" \
    -plugin "$BIN/protoc-gen-go-grpc-$PROTOC_GEN_GO_GRPC_VERSION" \
    -plugin "$BIN/protoc-gen-grpc-gateway-$GATEWAY_TAG")
done
for rcases in "$ROOT"/conformance/cases/request-*.json; do
  [ -e "$rcases" ] || continue
  name="$(basename "$rcases" .json)"
  name="${name#request-}"
  rtmp="$(mktemp "$ROOT/conformance/vectors/.request-$name.XXXXXX")"
  (cd "$WORK" && ABADA_GENERATOR="grpc-gateway $GATEWAY_TAG, protoc-gen-go-grpc $PROTOC_GEN_GO_GRPC_VERSION, $(go version | cut -d' ' -f3)" \
    go run ./internal/abadaoracle/e2e "$ROOT/conformance/contracts/$name.binpb" "$(cat "$ROOT/conformance/contracts/$name.source")") \
    < "$rcases" > "$rtmp"
  rout="$ROOT/conformance/vectors/request-$name.json"
  if [ "${1:-}" = "--check" ]; then
    if ! diff <(grep -v '"generator"' "$rout") <(grep -v '"generator"' "$rtmp") > /dev/null; then
      rm -f "$rtmp"
      echo "$rout is stale: run scripts/regen-vectors.sh" >&2
      exit 1
    fi
    rm -f "$rtmp"
  else
    mv "$rtmp" "$rout"
    echo "wrote $rout"
  fi
done

if [ "${1:-}" = "--check" ]; then
  # The Go version is recorded, not compared: the net/url rules it produced are.
  if ! diff <(grep -v '"generator"' "$out") <(grep -v '"generator"' "$tmp") > /dev/null; then
    echo "conformance/vectors/path.json is stale: run scripts/regen-vectors.sh" >&2
    exit 1
  fi
  echo "vectors match grpc-gateway $GATEWAY_TAG"
else
  mv "$tmp" "$out"
  echo "wrote $out"
fi
